version: '3.8'

services:
  backend:
    build: ./online_hackathon_backend
    container_name: backend
    expose:
      - "8001"
    networks:
      - app-network

  frontend:
    build: ./online_hackathon_frontend
    container_name: frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge